---
title: "BMI_final_project"
author: "Yuqi Tu, Yue (Lynette) Pan, Nadiya Pavlishyn, Shumin Rui"
date: "December 6, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readxl)
library(dplyr)
library(olsrr)
library(forcats)
```

```{r}
#####load in data
data = read_excel("GHProject_Dataset.xlsx") %>%
  janitor::clean_names() %>% 
  tidyr::separate(admitdtm, into = c("weekday", "admitdate"), sep = "day, ") %>%
  mutate(admitdate = gsub(", ", "/", admitdate)) %>% 
  tidyr::separate(admitdate, into = c("month", "dateyear"), sep = " ") %>% 
  mutate(month1 = match(month,month.name)) %>% 
  mutate(date = paste(stringr::str_sub(dateyear,-4,-1),"/",month1,"/",stringr::str_sub(dateyear,1,2),sep = "")) %>% 
  select(-month, -dateyear, -weekday, -month1) %>% 
  select(patientid, visitid, loshours, losdays2, is30dayreadmit, date, everything())

#arrange the data according to the time of admission
data = data[order(data$date),] 

#remove those more than one visits
data = data[!duplicated(data$patientid),]
data = data[!(data$is30dayreadmit == 1 & data$losdays2 > 30),]

#tidying: collapsing, setting indicator variables, 
#####descriptive statistics of each variable
##continuous variable
sum1 <- summary(data$losdays2,digits = 3) #transformation get good results
sum2 <- summary(data$ageyear,digits = 3) 
sum3 <- summary(data$bmi,digits = 3) #a lot of NA's
sum4 <- summary(data$bpsystolic,digits = 3)
sum5 <- summary(data$o2sat,digits = 3)
sum6 <- summary(data$temperature, digits = 3)
sum7 <- summary(data$heartrate, digits = 3)
sum8 <- summary(data$respirationrate, digits = 3)
sum9 <- summary(data$bpdiastolic, digits = 3)

knitr::kable(dplyr::bind_rows(
  c(variable = "Losdays2",sum1),#good to do log transform
  c(variable = "AgeYear", sum2),#quite normal
  c(variable = "bmi",sum3),#688 missing values and long tail, 3.1 min and 123 max, outlier/error
  c(variable = "bpsystolic", sum4),
  c(variable = "o2sat", sum5), # 10 observation below 90, 80 observation above 100, 2% of the data
  c(variable = "temperature", sum6), #3 less than 30 and 2 more than 50
  c(variable = "heartrate", sum7), # 2 more than 240 (rare heart rate or caused by disease)
  c(variable = "respirationrate", sum8),
  c(variable = "bpdiastolic", sum9)
))

##categorical variable
#MEWS: The Modified Early Warning Score (MEWS) 
#0-1=normal, 2-3=increase caution, 4-5=further deterioration, >5 immediate action required
table(data$mews)
#make them into 3 category and try to make the data balanced (though not perfect)
data$mews_catg<-ifelse(data$mews==0|data$mews==1,"normal",
                       ifelse(data$mews==2|data$mews==3,"increase caution",
                       ifelse(is.na(data$mews) == TRUE,NA,"fur deter or worse")))
data = data %>% mutate(mews_catg = fct_relevel(mews_catg,"increase caution"))
table(data$mews_catg)
#mews_catg: 1=normal; 2=increase caution; 3 = further deterioration or immediate action required

#Cindex -- Charlson comorbidity index (CCI) ranks patients based on severity of comorbidity: 0=normal, 1-2=mild, 3-4=moderate and >5=severe
table(data$cindex)
#make them into three category to balance the data
data$cindex_catg<-ifelse(data$cindex==0,"normal",
                         ifelse(data$cindex==1|data$cindex==2,"mild",
                         ifelse(is.na(data$cindex)==TRUE,NA,"moderate to severe")))
data = data %>% mutate(cindex_catg = fct_relevel(cindex_catg,"mild"))
table(data$cindex_catg)

#evisit
table(data$evisit)
data$evisit_catg<-ifelse(data$evisit==0|data$evisit==1,"No or1 visit",
                  ifelse(is.na(data$evisit)==TRUE,NA,"More than 1"))
data = data %>% mutate(evisit_catg = fct_relevel(evisit_catg,"No or1 visit"))
table(data$evisit_catg)
#evisit_catg:1=0 or 1 emergency department visit;2=more than once emergency department visit(may indicate the serious sickness)

#ICU_Flag: 1=if during hospitalization, the patient had a visit in the intensive care unit (ICU); 0=otherwise. 
table(data$icu_flag)
#gender: patient???s gender -- balanced
table(data$gender)
#race: patient???s race -- quite unbalanced
table(data$race)
data$race_catg<-ifelse(data$race=="White","White",
                ifelse(data$race=="African Amer/Black","African Amer/Black","Other race"))
data = data %>% mutate(race_catg = fct_relevel(race_catg, "White"))
table(data$race_catg)
#put other race together, might be controversal, but is more balanced

#religion: patient???s religion -- unbalanced, lets recode some
data$religion[data$religion == "Angelican"] <- "Christian"
data$religion[data$religion == "Non Denominational"] <- "Christian"
data$religion[data$religion == "Catholic"] <- "Christian"
data$religion[data$religion == "Hebrew"] <- "Jewish"
data$religion[data$religion == "Mormon"] <- "Other"
data = data %>% mutate(religion = fct_relevel(religion, "Christian"))
table(data$religion)


#MaritalStatus: patient???s marital status-- unbalanced
table(data$maritalstatus)
data$marital_catg <- ifelse(data$maritalstatus=="Civial            Union"|data$maritalstatus=="Married"|data$maritalstatus=="Civial Union","Not alone",
                      ifelse(data$maritalstatus=="Divorced"|data$maritalstatus=="Single"|
                             data$maritalstatus=="Widowed","Alone",NA))
table(data$marital_catg)
#InsuranceType: patient???s insurance
table(data$insurancetype)
data$insurance_catg <- ifelse(data$insurancetype=="Private","Private",
                        ifelse(data$insurancetype=="Medicaid"|data$insurancetype=="Medicare","Public",NA))
table(data$insurance_catg)

table(data$facilityname)



#visualize dataset for each variables
attach(data)
par(mfrow=c(3,3))
hist(losdays2) #highly skewed to the right
hist(ageyear)
hist(bmi)
hist(bpsystolic)
hist(o2sat)
hist(temperature)
hist(heartrate)
hist(respirationrate)
hist(bpdiastolic)

#try transformations of data
par(mfrow=c(1,1))
hist(log(data$losdays2)) #good to do log transform
```

```{r}
### try some simple linear regression
#continuous variable
summary(lm(log(losdays2)~ageyear,data = data))
summary(lm(log(losdays2)~bmi,data = data))
summary(lm(log(losdays2)~bpsystolic,data = data))
summary(lm(log(losdays2)~o2sat,data = data))
summary(lm(log(losdays2)~temperature,data = data))
summary(lm(log(losdays2)~log(heartrate),data = data))
summary(lm(log(losdays2)~log(respirationrate),data = data))
summary(lm(log(losdays2)~bpdiastolic,data = data))


#categorical varialbe
summary(lm(log(losdays2)~as.factor(mews_catg),data=data))
summary(lm(log(losdays2)~as.factor(cindex_catg),data=data))
summary(lm(log(losdays2)~as.factor(evisit_catg),data=data))
summary(lm(log(losdays2)~as.factor(icu_flag),data=data))
summary(lm(log(losdays2)~as.factor(gender),data=data))
summary(lm(log(losdays2)~as.factor(race_catg),data=data))
summary(lm(log(losdays2)~religion,data = data))
summary(lm(log(losdays2)~insurance_catg, data = data))
summary(lm(log(losdays2)~marital_catg, data = data))


###replace missing bmi with the mean of the rest
replace_missing_value = function(vec){
#for numeric vectors, fill in missing values with the mean or median of non-missing values
  vec[is.na(vec)] = round(mean(vec,na.rm = TRUE),1)
  vec #return the vector
}
data$bmi = replace_missing_value(data$bmi)

###try to make bmi into categorical variable
#reference: http://apps.who.int/bmi/index.jsp?introPage=intro_3.html
#<18.5 underweight
#18.5-24.99 normal
#25-29.99 pre-obese
#>30 obese

data$bmi_catg<-ifelse(data$bmi<18.5,"underweight",
                ifelse(data$bmi<25,"normal",
                ifelse(data$bmi<30,"pre-obese",
                ifelse(data$bmi>=30,"obese",NA))))
table(data$bmi_catg)
summary(lm(log(losdays2)~bmi_catg,data=data))
###try to separate the data into icu_flag = 0 and icu_flag = 1
data_icu0 = data[data$icu_flag==0,]
data_icu1 = data[data$icu_flag==1,]
###try to separate the data into "alone" and "not along"
data_alone = data[data$marital_catg == "Alone",]
data_notalone = data[data$marital_catg == "Not alone",]
```

```{r}
###build the main model
whole_model = lm(log(losdays2) ~ ageyear+mews_catg+
                 as.factor(cindex)+as.factor(evisit)+icu_flag+
                 gender+race_catg+insurance_catg+marital_catg+bmi_catg+facilityname,
                 data = data)
HH::vif(whole_model)
#religion have very very high VIF score, then we remove it from our final model

#try to separate the dataset with icu_flag==0 and icu_flag==1

###try automatic procedure
#backward procedure based on AIC
step(whole_model, direction='backward')
summary(lm(formula = log(losdays2) ~ ageyear + mews_catg + as.factor(cindex) + 
    as.factor(evisit) + gender + insurance_catg + marital_catg + 
    bmi_catg + facilityname, data = data))
#stepwise regression based on AIC
ols_stepaic_both(whole_model)
summary(lm(log(losdays2) ~ mews_catg + marital_catg + insurance_catg + as.factor(evisit) + ageyear + as.factor(cindex)+
             bmi_catg+facilityname+gender, data = data))


###criterion procedure

###model diagnostics

###cross validation/bootstrap
```



